export type Project = {
  id: number;
  slug: string;
  title: string;
  link: string;
  tech: string[];
  industry: string;
  service: string;
  emoji: string;
  summary: {
    en: string;
    id: string;
  };
};

export const projectEmojis = ["🏢", "📚", "🎨", "🌿", "🌍", "🇯🇵", "👔", "⚖️", "💰", "✈️", "🧠", "📈", "🤝", "🚗", "🧪", "🛡️"];

export const iconColors = [
  { bg: "#fef3c7" },
  { bg: "#dbeafe" },
  { bg: "#d1fae5" },
  { bg: "#fce7f3" },
  { bg: "#e0e7ff" },
  { bg: "#fef9c3" },
  { bg: "#f3e8ff" },
  { bg: "#ffe4e6" },
  { bg: "#ccfbf1" },
  { bg: "#e0f2fe" },
];

export const projects: Project[] = [
  {
    id: 44,
    slug: "polosinaja",
    title: "Polosinaja",
    link: "https://web.archive.org/web/20250411042015/https://polosinaja.com/",
    tech: ["E-Commerce", "Fashion", "Store"],
    industry: "Fashion retail",
    service: "E-commerce website",
    emoji: "🏢",
    summary: {
      en: "An e-commerce storefront for plain and basic apparel across men's, women's, and children's categories, designed to make product discovery clear and purchasing straightforward.",
      id: "Toko online untuk pakaian polos dan basic bagi pria, wanita, dan anak-anak, dirancang agar pencarian produk jelas dan proses belanja terasa mudah.",
    },
  },
  {
    id: 45,
    slug: "svingolf-apparel",
    title: "Svingolf Apparel",
    link: "https://svingolf.com/",
    tech: ["E-Commerce", "Apparel", "Golf"],
    industry: "Golf apparel",
    service: "E-commerce and brand website",
    emoji: "🏌️",
    summary: {
      en: "A premium golf apparel website presenting ready-stock products and custom uniform services with a polished brand experience for individual and corporate buyers.",
      id: "Website apparel golf premium yang menampilkan produk ready stock dan layanan seragam custom dengan pengalaman brand yang rapi untuk pembeli individu maupun korporat.",
    },
  },
  {
    id: 1,
    slug: "pt-dananjaya-zafer-adibrata",
    title: "PT Dananjaya Zafer Adibrata",
    link: "https://dzagroup.co.id/",
    tech: ["Web Profile", "Business", "Consulting"],
    industry: "Business consulting",
    service: "Company profile website",
    emoji: "🏢",
    summary: {
      en: "A corporate profile for a business licensing and company formation consultant, built to communicate credibility, services, and consultation paths clearly.",
      id: "Company profile untuk konsultan perizinan bisnis dan pendirian perusahaan, dibuat untuk menyampaikan kredibilitas, layanan, dan jalur konsultasi dengan jelas.",
    },
  },
  {
    id: 2,
    slug: "haloexpert",
    title: "HALOEXPERT",
    link: "https://haloexpert.id",
    tech: ["LMS", "Education", "Platform"],
    industry: "Education technology",
    service: "Learning management system",
    emoji: "📚",
    summary: {
      en: "A learning management platform that helps training providers organize online education programs, learning content, and participant access in one structured experience.",
      id: "Platform learning management yang membantu penyedia pelatihan mengelola program edukasi online, konten pembelajaran, dan akses peserta dalam satu pengalaman terstruktur.",
    },
  },
  {
    id: 3,
    slug: "meja-kreatif-studio",
    title: "Meja Kreatif Studio",
    link: "https://mejakreatif.com",
    tech: ["Creative", "Branding", "UI/UX"],
    industry: "Creative agency",
    service: "Studio website",
    emoji: "🎨",
    summary: {
      en: "A modern creative studio website focused on presenting brand strategy, digital visuals, and design services through a clean and memorable interface.",
      id: "Website studio kreatif modern yang menampilkan strategi brand, visual digital, dan layanan desain melalui antarmuka yang bersih dan mudah diingat.",
    },
  },
  {
    id: 4,
    slug: "yayasan-petai",
    title: "Yayasan PETAI",
    link: "https://petai.or.id",
    tech: ["Non-Profit", "Environment", "NGO"],
    industry: "Non-profit",
    service: "Organization profile",
    emoji: "🌿",
    summary: {
      en: "An organization profile for an environmental foundation, structured to explain conservation programs, mission, and public impact with accessible storytelling.",
      id: "Profil organisasi untuk yayasan lingkungan, disusun untuk menjelaskan program konservasi, misi, dan dampak publik melalui cerita yang mudah dipahami.",
    },
  },
  {
    id: 5,
    slug: "ekspora",
    title: "EKSPORA",
    link: "https://ekspora.com",
    tech: ["SME", "Export", "Platform"],
    industry: "Export enablement",
    service: "SME platform",
    emoji: "🌍",
    summary: {
      en: "A digital platform supporting SMEs as they explore international export opportunities, with messaging centered on readiness, guidance, and market access.",
      id: "Platform digital yang mendukung UMKM memasuki peluang ekspor internasional, dengan pesan utama seputar kesiapan, pendampingan, dan akses pasar.",
    },
  },
  {
    id: 6,
    slug: "japan-shiken-shop",
    title: "Japan Shiken Shop",
    link: "https://japanshiken.com",
    tech: ["E-Commerce", "Niche", "Store"],
    industry: "Japanese niche retail",
    service: "E-commerce website",
    emoji: "🇯🇵",
    summary: {
      en: "A niche e-commerce store serving Japan-focused products and audiences, built around focused catalog navigation and clear product positioning.",
      id: "Toko online niche untuk produk dan audiens bertema Jepang, dibangun dengan navigasi katalog yang fokus dan positioning produk yang jelas.",
    },
  },
  {
    id: 7,
    slug: "the-business-tailor",
    title: "The Business Tailor",
    link: "https://thebusinesstailor.com.sg",
    tech: ["Corporate", "Strategy", "B2B"],
    industry: "Business strategy",
    service: "Corporate website",
    emoji: "👔",
    summary: {
      en: "A B2B corporate website for bespoke business strategy and branding services, designed to make the consulting offer feel premium and precise.",
      id: "Website korporat B2B untuk layanan strategi bisnis dan branding yang personal, dirancang agar penawaran konsultasi terasa premium dan tepat sasaran.",
    },
  },
  {
    id: 9,
    slug: "duniafintech",
    title: "DUNIAFINTECH",
    link: "https://duniafintech.com",
    tech: ["Fintech", "SEO", "Optimization"],
    industry: "Financial media",
    service: "SEO and performance optimization",
    emoji: "💰",
    summary: {
      en: "A fintech news platform optimized for search visibility, publishing performance, and fast access to finance-related content.",
      id: "Platform berita fintech yang dioptimasi untuk visibilitas pencarian, performa publikasi, dan akses cepat ke konten seputar keuangan.",
    },
  },
  {
    id: 10,
    slug: "alkhair-tour-and-travel",
    title: "Alkhair Tour and Travel",
    link: "https://alkhaitravel.id",
    tech: ["Travel", "Agency", "Gallery"],
    industry: "Travel agency",
    service: "Travel website",
    emoji: "✈️",
    summary: {
      en: "A travel agency website presenting trip packages, destination highlights, and service information for customers planning reliable travel experiences.",
      id: "Website agen perjalanan yang menampilkan paket wisata, highlight destinasi, dan informasi layanan untuk pelanggan yang merencanakan perjalanan tepercaya.",
    },
  },
  {
    id: 11,
    slug: "praktiqu",
    title: "Praktiqu",
    link: "https://event.praktiqu.com",
    tech: ["Consulting", "Psychology", "Agency"],
    industry: "Psychology consulting",
    service: "Event and agency website",
    emoji: "🧠",
    summary: {
      en: "A psychology consulting and event website that introduces professional programs, expert-led sessions, and audience-focused mental wellness services.",
      id: "Website event dan konsultasi psikologi yang memperkenalkan program profesional, sesi bersama ahli, dan layanan kesehatan mental yang relevan untuk audiens.",
    },
  },
  {
    id: 12,
    slug: "evrando-seo",
    title: "Evrando SEO",
    link: "https://evrando.com",
    tech: ["SEO", "Keyword Research", "Analytics"],
    industry: "Search optimization",
    service: "SEO case study",
    emoji: "📈",
    summary: {
      en: "An SEO case study focused on improving keyword visibility and organic performance for targeted commercial search terms.",
      id: "Studi kasus SEO yang berfokus meningkatkan visibilitas keyword dan performa organik untuk kata kunci komersial yang ditargetkan.",
    },
  },
  {
    id: 13,
    slug: "kolaborasa",
    title: "Kolaborasa",
    link: "https://kolaborasa.id",
    tech: ["Platform", "System", "Collaboration"],
    industry: "Collaboration platform",
    service: "Web system",
    emoji: "🤝",
    summary: {
      en: "A web-based collaboration system designed to support team coordination, platform management, and structured digital workflows.",
      id: "Sistem kolaborasi berbasis web yang dirancang untuk mendukung koordinasi tim, manajemen platform, dan alur kerja digital yang terstruktur.",
    },
  },
  {
    id: 14,
    slug: "mulya-rental-mobil",
    title: "Mulya Rental Mobil",
    link: "https://mulyarentalmobil.com",
    tech: ["Travel", "Rent Car", "Service"],
    industry: "Transportation",
    service: "Service website",
    emoji: "🚗",
    summary: {
      en: "A rental car and travel service website that helps customers understand vehicle options, service coverage, and booking paths quickly.",
      id: "Website rental mobil dan layanan travel yang membantu pelanggan memahami pilihan kendaraan, cakupan layanan, dan jalur pemesanan dengan cepat.",
    },
  },
  {
    id: 15,
    slug: "bpt-klin",
    title: "BPT KLIN",
    link: "https://bptklin.com",
    tech: ["Chemical", "Product", "Industry"],
    industry: "Cleaning products",
    service: "Product website",
    emoji: "🧪",
    summary: {
      en: "A product website for professional chemical soap and cleaning solutions, organized to explain product value, use cases, and industrial credibility.",
      id: "Website produk chemical soap dan solusi kebersihan profesional, disusun untuk menjelaskan nilai produk, kegunaan, dan kredibilitas industri.",
    },
  },
  {
    id: 16,
    slug: "asia-safety-pro",
    title: "Asia Safety Pro",
    link: "https://asiasafety.pro",
    tech: ["Security", "Protection", "Service"],
    industry: "Security services",
    service: "Service website",
    emoji: "🛡️",
    summary: {
      en: "A professional security service website presenting protection guard solutions with clear service positioning and trust-focused communication.",
      id: "Website layanan keamanan profesional yang menampilkan solusi protection guard dengan positioning layanan yang jelas dan komunikasi yang membangun kepercayaan.",
    },
  },
  {
    id: 17,
    slug: "hiiboss-ai",
    title: "HiiBoss AI",
    link: "https://hiiboss.ai/",
    tech: ["AI", "Automation", "Platform"],
    industry: "Artificial intelligence",
    service: "AI platform website",
    emoji: "🤖",
    summary: {
      en: "An AI-powered business automation platform positioned around intelligent agents, operational efficiency, and smarter workflow management.",
      id: "Platform otomasi bisnis berbasis AI yang diposisikan melalui intelligent agents, efisiensi operasional, dan manajemen workflow yang lebih cerdas.",
    },
  },
  {
    id: 18,
    slug: "shopfoodie-ai",
    title: "ShopFoodie AI",
    link: "https://shopfoodie-ai.com/",
    tech: ["E-Commerce", "AI", "FoodTech"],
    industry: "Food technology",
    service: "AI commerce platform",
    emoji: "🍽️",
    summary: {
      en: "An AI-driven culinary commerce platform connecting recipe inspiration, personalized recommendations, and smarter grocery shopping.",
      id: "Platform commerce kuliner berbasis AI yang menghubungkan inspirasi resep, rekomendasi personal, dan pengalaman belanja bahan makanan yang lebih cerdas.",
    },
  },
  {
    id: 19,
    slug: "vive-software",
    title: "Vive Software",
    link: "https://vive.software/",
    tech: ["Software", "Enterprise", "Consulting"],
    industry: "Software consulting",
    service: "Technology website",
    emoji: "💻",
    summary: {
      en: "A technology consulting website for scalable software solutions, enterprise systems, and digital transformation services.",
      id: "Website konsultasi teknologi untuk solusi software yang scalable, sistem enterprise, dan layanan transformasi digital.",
    },
  },
  {
    id: 20,
    slug: "ecobis",
    title: "EcoBis",
    link: "https://ecobis.web.id/",
    tech: ["Business", "Eco", "Education"],
    industry: "Sustainable business",
    service: "Education and consulting website",
    emoji: "🌱",
    summary: {
      en: "An eco-conscious business education and consulting platform that connects entrepreneurs with practical sustainability guidance.",
      id: "Platform edukasi dan konsultasi bisnis ramah lingkungan yang menghubungkan pelaku usaha dengan panduan keberlanjutan yang praktis.",
    },
  },
  {
    id: 21,
    slug: "ekspresi",
    title: "Ekspresi",
    link: "https://ekspresi.co",
    tech: ["Media", "Creative", "Content"],
    industry: "Digital media",
    service: "Content portal",
    emoji: "📝",
    summary: {
      en: "A digital media portal built as a creative publishing space for stories, ideas, and content from emerging voices.",
      id: "Portal media digital sebagai ruang publikasi kreatif untuk cerita, ide, dan konten dari para kreator.",
    },
  },
  {
    id: 22,
    slug: "grizmedia",
    title: "GrizMedia",
    link: "https://grizmedia.id",
    tech: ["Digital Agency", "Media", "Marketing"],
    industry: "Digital marketing",
    service: "Agency website",
    emoji: "📣",
    summary: {
      en: "A full-service digital media agency website covering content production, social media management, and marketing strategy.",
      id: "Website agensi media digital full-service yang mencakup produksi konten, manajemen media sosial, dan strategi pemasaran.",
    },
  },
  {
    id: 23,
    slug: "kos-rumah-arafah",
    title: "Kos Rumah Arafah",
    link: "https://kosrumaharafah.com",
    tech: ["Property", "Kos", "Listing"],
    industry: "Property rental",
    service: "Listing website",
    emoji: "🏠",
    summary: {
      en: "A property listing website for exclusive boarding rooms, helping students and professionals evaluate facilities and housing options with confidence.",
      id: "Website listing kos eksklusif yang membantu mahasiswa dan profesional mengevaluasi fasilitas serta pilihan hunian dengan percaya diri.",
    },
  },
  {
    id: 24,
    slug: "vox-ai-indonesia",
    title: "Vox AI Indonesia",
    link: "https://voxaindonesia.id",
    tech: ["AI", "Voice Tech", "Indonesia"],
    industry: "Voice AI",
    service: "AI technology website",
    emoji: "🎙️",
    summary: {
      en: "An Indonesian AI technology platform presenting voice recognition and natural language processing solutions for local business needs.",
      id: "Platform teknologi AI Indonesia yang menampilkan solusi voice recognition dan natural language processing untuk kebutuhan bisnis lokal.",
    },
  },
  {
    id: 25,
    slug: "ayai",
    title: "Ayai",
    link: "https://ayai.my",
    tech: ["AI", "Automation", "SaaS"],
    industry: "AI productivity",
    service: "SaaS website",
    emoji: "✨",
    summary: {
      en: "An AI productivity solution designed to help individuals and businesses automate tasks and improve daily workflows.",
      id: "Solusi produktivitas berbasis AI yang dirancang untuk membantu individu dan bisnis mengotomatisasi tugas serta meningkatkan workflow harian.",
    },
  },
  {
    id: 26,
    slug: "kapten-seo",
    title: "Kapten SEO",
    link: "https://kaptenseo.com",
    tech: ["SEO", "PageSpeed", "Optimization"],
    industry: "Search optimization",
    service: "SEO and PageSpeed service",
    emoji: "⚡",
    summary: {
      en: "A technical SEO and PageSpeed service website focused on Core Web Vitals, search performance, and faster user experiences.",
      id: "Website layanan SEO teknikal dan PageSpeed yang berfokus pada Core Web Vitals, performa pencarian, dan pengalaman pengguna yang lebih cepat.",
    },
  },
  {
    id: 27,
    slug: "cendekia-privat",
    title: "Cendekia Privat",
    link: "https://cendekiaprivat.com/",
    tech: ["Education", "Tutoring", "PageSpeed"],
    industry: "Private tutoring",
    service: "Education website optimization",
    emoji: "🎓",
    summary: {
      en: "A premium tutoring platform optimized for performance, helping students and parents connect with experienced private tutors online.",
      id: "Platform les privat premium yang dioptimasi performanya untuk membantu siswa dan orang tua terhubung dengan tutor berpengalaman secara online.",
    },
  },
  {
    id: 28,
    slug: "monster-diving",
    title: "Monster Diving",
    link: "https://monsterdiving.com/",
    tech: ["Tourism", "Diving", "Adventure"],
    industry: "Adventure tourism",
    service: "Tourism website",
    emoji: "🤿",
    summary: {
      en: "A premium diving tourism website presenting underwater trips, certified guides, and Indonesian marine destinations with an adventurous brand tone.",
      id: "Website wisata diving premium yang menampilkan paket menyelam, pemandu bersertifikat, dan destinasi laut Indonesia dengan tone brand petualangan.",
    },
  },
  {
    id: 29,
    slug: "sara-international-travel",
    title: "Sara International Travel",
    link: "https://sarainternationaltravel.com/",
    tech: ["Travel", "International", "Agency"],
    industry: "International travel",
    service: "Travel agency website",
    emoji: "🕋",
    summary: {
      en: "An international travel agency website for tourism, umrah, hajj, and premium travel services across global destinations.",
      id: "Website agen perjalanan internasional untuk wisata, umrah, haji, dan layanan travel premium ke berbagai destinasi dunia.",
    },
  },
  {
    id: 30,
    slug: "bali-travel-store",
    title: "Bali Travel Store",
    link: "https://balitravel.store/",
    tech: ["Travel", "Bali", "E-Commerce"],
    industry: "Bali tourism",
    service: "Travel commerce website",
    emoji: "🏝️",
    summary: {
      en: "An online travel store for Bali experiences, combining local activities, cultural tours, and nature adventures in a commerce-ready format.",
      id: "Toko online untuk pengalaman wisata Bali yang menggabungkan aktivitas lokal, tur budaya, dan petualangan alam dalam format siap transaksi.",
    },
  },
  {
    id: 31,
    slug: "halalfun",
    title: "HalalFun",
    link: "https://halalfun.id/",
    tech: ["Halal", "Company Website", "Service"],
    industry: "Halal service",
    service: "Company website",
    emoji: "✅",
    summary: {
      en: "A company website project for HalalFun, built around a clean professional presence and the main public domain at halalfun.id.",
      id: "Project website perusahaan untuk HalalFun, dibuat sebagai kehadiran profesional yang rapi dengan domain utama di halalfun.id.",
    },
  },
  {
    id: 32,
    slug: "bank-minyak-jelantah",
    title: "Bank Minyak Jelantah",
    link: "https://bankminyakjelantah.com",
    tech: ["Environment", "Waste Management", "Green"],
    industry: "Waste management",
    service: "Environmental platform",
    emoji: "♻️",
    summary: {
      en: "An environmental platform for collecting used cooking oil and turning kitchen waste into a more valuable, responsible resource.",
      id: "Platform lingkungan untuk pengumpulan minyak jelantah bekas dan mengubah limbah dapur menjadi sumber daya yang lebih bernilai serta bertanggung jawab.",
    },
  },
  {
    id: 33,
    slug: "malindo-mega-utama",
    title: "Malindo Mega Utama",
    link: "https://malindomegautama.com",
    tech: ["SEO", "Optimization", "B2B"],
    industry: "Distribution and trading",
    service: "SEO optimization",
    emoji: "📦",
    summary: {
      en: "A B2B SEO optimization project for a distribution and trading company, focused on improving organic visibility for priority business keywords.",
      id: "Project optimasi SEO B2B untuk perusahaan distribusi dan perdagangan, berfokus meningkatkan visibilitas organik untuk keyword bisnis prioritas.",
    },
  },
  {
    id: 34,
    slug: "warta-gaul",
    title: "Warta Gaul",
    link: "https://wartagaul.biz.id",
    tech: ["News Portal", "Media", "Entertainment"],
    industry: "Youth media",
    service: "News portal",
    emoji: "📰",
    summary: {
      en: "A youth-focused news and entertainment portal designed for trending content, lifestyle updates, and light digital culture coverage.",
      id: "Portal berita dan hiburan anak muda yang dirancang untuk konten trending, gaya hidup, dan liputan budaya digital yang ringan.",
    },
  },
  {
    id: 35,
    slug: "kilas-kabar",
    title: "Kilas Kabar",
    link: "https://kilaskabar.biz.id",
    tech: ["News Portal", "Media", "Indonesia"],
    industry: "Online news",
    service: "News portal",
    emoji: "🗞️",
    summary: {
      en: "A fast-read Indonesian news portal built around concise updates, broad national coverage, and easy-to-scan article discovery.",
      id: "Portal berita Indonesia dengan format baca cepat, cakupan nasional yang luas, dan penemuan artikel yang mudah dipindai.",
    },
  },
  {
    id: 36,
    slug: "suara24",
    title: "Suara24",
    link: "https://suara24.com",
    tech: ["News Portal", "Media", "24 Hours"],
    industry: "Online news",
    service: "News portal",
    emoji: "📡",
    summary: {
      en: "A 24-hour online news media website covering national and regional issues with emphasis on speed, structure, and editorial clarity.",
      id: "Website media berita online 24 jam yang meliput isu nasional dan daerah dengan fokus pada kecepatan, struktur, dan kejelasan editorial.",
    },
  },
  {
    id: 37,
    slug: "pelopor-sumut",
    title: "Pelopor Sumut",
    link: "https://peloporsumut.com",
    tech: ["News Portal", "Regional", "Sumut"],
    industry: "Regional media",
    service: "News portal",
    emoji: "📍",
    summary: {
      en: "A North Sumatra regional media portal covering local politics, economy, society, and culture through a structured digital publication.",
      id: "Portal media regional Sumatera Utara yang meliput politik lokal, ekonomi, sosial, dan budaya melalui publikasi digital yang terstruktur.",
    },
  },
  {
    id: 38,
    slug: "fakta-sumut",
    title: "Fakta Sumut",
    link: "https://faktasumut.com",
    tech: ["News Portal", "Regional", "Sumut"],
    industry: "Regional media",
    service: "News portal",
    emoji: "✅",
    summary: {
      en: "A factual regional news portal for North Sumatra, designed to present balanced coverage of local events and area developments.",
      id: "Portal berita faktual Sumatera Utara yang dirancang untuk menyajikan liputan berimbang seputar peristiwa lokal dan perkembangan daerah.",
    },
  },
  {
    id: 39,
    slug: "bedah-kasus",
    title: "Bedah Kasus",
    link: "https://bedahkasus.com",
    tech: ["News Portal", "Law", "Media"],
    industry: "Legal media",
    service: "News portal",
    emoji: "⚖️",
    summary: {
      en: "A legal and criminal news portal focused on case analysis, current legal developments, and expert-led editorial framing.",
      id: "Portal berita hukum dan kriminal yang berfokus pada analisis kasus, perkembangan hukum terkini, dan framing editorial berbasis keahlian.",
    },
  },
  {
    id: 40,
    slug: "slonidi",
    title: "Slonidi",
    link: "https://slonidi.com",
    tech: ["Platform", "Digital", "Service"],
    industry: "Digital services",
    service: "Platform website",
    emoji: "🔧",
    summary: {
      en: "A digital service platform presented around convenience, speed, and practical modern solutions for everyday user needs.",
      id: "Platform layanan digital yang dipresentasikan melalui kemudahan, kecepatan, dan solusi modern praktis untuk kebutuhan pengguna sehari-hari.",
    },
  },
  {
    id: 41,
    slug: "portal-banggai",
    title: "Portal Banggai",
    link: "https://portalbanggai.com",
    tech: ["News Portal", "Regional", "Media"],
    industry: "Regional media",
    service: "News portal",
    emoji: "🌐",
    summary: {
      en: "A local news portal for Banggai Regency, built to support timely coverage of public affairs, government updates, and community stories.",
      id: "Portal berita lokal Kabupaten Banggai yang dibangun untuk mendukung liputan aktual seputar urusan publik, pemerintahan, dan cerita masyarakat.",
    },
  },
  {
    id: 42,
    slug: "rotari",
    title: "Rotari",
    link: "https://rotari.id/",
    tech: ["SEO", "Malware Removal", "Security"],
    industry: "Website recovery",
    service: "SEO and security cleanup",
    emoji: "🛡️",
    summary: {
      en: "A technical recovery project combining SEO optimization and malware cleanup to restore website performance, security, and search trust.",
      id: "Project pemulihan teknikal yang menggabungkan optimasi SEO dan pembersihan malware untuk mengembalikan performa, keamanan, dan kepercayaan pencarian.",
    },
  },
  {
    id: 43,
    slug: "beaufo-id",
    title: "Beaufo.id",
    link: "https://web.archive.org/web/20210301044419/https://beaufo.id/",
    tech: ["E-Commerce", "Beauty", "Lifestyle"],
    industry: "Beauty commerce",
    service: "E-commerce website",
    emoji: "💄",
    summary: {
      en: "A beauty and personal care e-commerce platform designed to present curated products through an elegant and approachable shopping experience.",
      id: "Platform e-commerce kecantikan dan perawatan diri yang dirancang untuk menampilkan produk pilihan melalui pengalaman belanja yang elegan dan mudah didekati.",
    },
  },
];

export function getProjectBySlug(slug: string) {
  return projects.find((project) => project.slug === slug);
}

export function getProjectNarrative(project: Project) {
  return {
    en: {
      role: `${project.service} for the ${project.industry.toLowerCase()} space.`,
      approach: `The project needed a focused digital presence that could explain the offer, guide visitors through the most important information, and make the next action obvious. The structure emphasizes clear messaging, concise sections, and conversion-oriented navigation.`,
      outcome: `${project.title} now has a professional project presentation that supports credibility, product or service discovery, and stronger communication with its intended audience.`,
    },
    id: {
      role: `${project.service} untuk bidang ${project.industry.toLowerCase()}.`,
      approach: `Project ini membutuhkan kehadiran digital yang fokus untuk menjelaskan penawaran, mengarahkan pengunjung ke informasi terpenting, dan membuat langkah berikutnya terasa jelas. Strukturnya menekankan pesan yang rapi, section yang ringkas, dan navigasi yang berorientasi konversi.`,
      outcome: `${project.title} kini memiliki presentasi project yang profesional untuk mendukung kredibilitas, penemuan produk atau layanan, dan komunikasi yang lebih kuat dengan audiens yang dituju.`,
    },
  };
}
